################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_3des.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_aes.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_des.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_md5.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_sha.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_md5.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_prf.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_rsa.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_sha.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_rng_self_test.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_table_self_test.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_module_hash_compute.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_active_certificate_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_allocate_handshake_packet.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_check_protocol_version.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ciphersuite_lookup.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_handshake.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_psk_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_clienthello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_find_curve_method.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_keys.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_premaster_secret.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_request.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_client_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_server_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_request.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_client_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_server_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_finished_hash_generate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_keys.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_premaster_secret.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_init.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_update.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_process.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_hash_record.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_key_material_init.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_map_error_to_alert.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_metadata_size_calculate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_newest_supported_version.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_packet_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_request.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_changecipherspec.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_client_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_finished.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_handshake_header.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_header.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_record.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_remote_certificate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_server_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_protocol_version_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_calculate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_update.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_decrypt.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_encrypt.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_buffer_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free_all.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_alert.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_request.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_changecipherspec.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_client_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_finished.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_handshake_record.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_hellorequest.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_record.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_server_key_exchange.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello_extensions.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_handshake.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_alert_value_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_certificate_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_disable.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_enable.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_create.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_delete.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_end.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_iv_size_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_keys_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_packet_buffer_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_protocol_version_override.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive_records.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_reset.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_send.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_server_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_start.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_time_function_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_x509_client_verify_configure.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_verify_mac.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_asn1_tlv_block_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_chain_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_revocation_list_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_common_name_dns_check.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_revocation_check.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_compare.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_dns_name_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ec_private_key_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_revocation_list_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_crl_verify.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_oid_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_expiration_check.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extended_key_usage_extension_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extension_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_find_certificate_methods.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_free_certificate_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_key_usage_extension_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_device_certificate_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_oid_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs1_rsa_private_key_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs7_decode.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_remote_endpoint_certificate_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_subject_alt_names_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_wildcard_compare.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_active_certificate_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_client_psk_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_metadata_size_calculate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_packet_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_psk_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_buffer_allocate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_free_all.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_alert_value_get.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_certificate_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_disable.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_enable.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_create.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_delete.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_end.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_packet_buffer_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_protocol_version_override.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_receive.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_reset.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_send.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_server_callback_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_start.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_time_function_set.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_x509_client_verify_configure.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_add.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_remove.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_certificate_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_common_name_dns_check.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_crl_revocation_check.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_dns_name_initialize.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extended_key_usage_extension_parse.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extension_find.c \
../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_key_usage_extension_parse.c 

OBJS += \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_3des.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_aes.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_des.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_md5.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_sha.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_md5.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_prf.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_rsa.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_sha.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_rng_self_test.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_table_self_test.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_module_hash_compute.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_active_certificate_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_allocate_handshake_packet.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_check_protocol_version.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ciphersuite_lookup.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_handshake.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_psk_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_clienthello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_find_curve_method.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_keys.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_premaster_secret.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_request.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_client_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_server_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_request.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_client_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_server_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_finished_hash_generate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_keys.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_premaster_secret.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_init.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_update.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_process.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_hash_record.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_key_material_init.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_map_error_to_alert.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_metadata_size_calculate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_newest_supported_version.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_packet_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_request.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_changecipherspec.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_client_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_finished.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_handshake_header.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_header.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_record.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_remote_certificate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_server_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_protocol_version_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_calculate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_update.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_decrypt.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_encrypt.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_buffer_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free_all.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_alert.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_request.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_changecipherspec.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_client_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_finished.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_handshake_record.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_hellorequest.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_record.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_server_key_exchange.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello_extensions.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_handshake.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_alert_value_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_certificate_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_disable.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_enable.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_create.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_delete.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_end.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_iv_size_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_keys_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_packet_buffer_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_protocol_version_override.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive_records.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_reset.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_send.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_server_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_start.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_time_function_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_x509_client_verify_configure.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_verify_mac.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_asn1_tlv_block_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_chain_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_revocation_list_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_common_name_dns_check.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_revocation_check.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_compare.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_dns_name_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ec_private_key_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_revocation_list_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_crl_verify.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_oid_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_expiration_check.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extended_key_usage_extension_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extension_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_find_certificate_methods.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_free_certificate_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_key_usage_extension_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_device_certificate_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_oid_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs1_rsa_private_key_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs7_decode.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_remote_endpoint_certificate_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_subject_alt_names_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_wildcard_compare.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_active_certificate_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_client_psk_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_metadata_size_calculate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_packet_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_psk_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_buffer_allocate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_free_all.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_alert_value_get.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_certificate_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_disable.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_enable.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_create.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_delete.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_end.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_packet_buffer_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_protocol_version_override.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_receive.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_reset.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_send.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_server_callback_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_start.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_time_function_set.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_x509_client_verify_configure.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_add.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_remove.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_certificate_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_common_name_dns_check.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_crl_revocation_check.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_dns_name_initialize.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extended_key_usage_extension_parse.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extension_find.o \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_key_usage_extension_parse.o 

C_DEPS += \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_3des.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_aes.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_des.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_md5.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_hmac_sha.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_md5.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_prf.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_rsa.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_method_self_test_sha.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_rng_self_test.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_crypto_table_self_test.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_module_hash_compute.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_active_certificate_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_allocate_handshake_packet.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_check_protocol_version.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ciphersuite_lookup.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_handshake.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_client_psk_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_clienthello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_find_curve_method.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_keys.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_generate_premaster_secret.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_request.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_client_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_clienthello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_process_server_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_request.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_client_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_ecc_send_server_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_finished_hash_generate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_keys.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_generate_premaster_secret.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_init.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_hash_update.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_handshake_process.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_hash_record.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_key_material_init.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_local_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_map_error_to_alert.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_metadata_size_calculate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_newest_supported_version.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_packet_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_request.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_changecipherspec.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_client_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_clienthello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_finished.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_handshake_header.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_header.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_record.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_remote_certificate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_server_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_process_serverhello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_protocol_version_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_psk_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_calculate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_hash_update.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_decrypt.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_record_payload_encrypt.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_buffer_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_free_all.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_remote_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_alert.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_request.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_changecipherspec.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_client_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_clienthello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_finished.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_handshake_record.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_hellorequest.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_record.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_server_key_exchange.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_send_serverhello_extensions.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_server_handshake.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_alert_value_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_certificate_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_disable.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_client_verify_enable.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_create.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_delete.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_end.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_iv_size_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_keys_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_packet_buffer_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_protocol_version_override.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_receive_records.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_renegotiate_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_reset.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_send.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_server_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_sni_extension_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_start.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_time_function_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_session_x509_client_verify_configure.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_trusted_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_tls_verify_mac.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_asn1_tlv_block_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_chain_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_list_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_revocation_list_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_common_name_dns_check.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_revocation_check.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_crl_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_compare.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_distinguished_name_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_dns_name_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ec_private_key_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_revocation_list_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_certificate_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_crl_verify.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_ecc_oid_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_expiration_check.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extended_key_usage_extension_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_extension_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_find_certificate_methods.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_free_certificate_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_key_usage_extension_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_local_device_certificate_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_oid_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs1_rsa_private_key_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_pkcs7_decode.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_remote_endpoint_certificate_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_store_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_subject_alt_names_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nx_secure_x509_wildcard_compare.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_active_certificate_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_client_psk_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_local_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_metadata_size_calculate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_packet_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_psk_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_buffer_allocate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_remote_certificate_free_all.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_server_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_alert_value_get.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_certificate_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_disable.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_client_verify_enable.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_create.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_delete.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_end.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_packet_buffer_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_protocol_version_override.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_receive.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_renegotiate_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_reset.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_send.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_server_callback_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_sni_extension_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_start.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_time_function_set.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_session_x509_client_verify_configure.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_add.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_tls_trusted_certificate_remove.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_certificate_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_common_name_dns_check.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_crl_revocation_check.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_dns_name_initialize.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extended_key_usage_extension_parse.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_extension_find.d \
./synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/nxe_secure_x509_key_usage_extension_parse.d 


# Each subdirectory must supply rules for building sources it contributes
synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/%.o: ../synergy/ssp/src/framework/el/nxd_application_layer/nxd_tls_secure/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM Cross C Compiler'
	F:\Renesas\e2_studio\Utilities\\/isdebuild arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g3 -D_RENESAS_SYNERGY_ -I"K:\GitHub\adc_s5d9\EMS\synergy_cfg\ssp_cfg\bsp" -I"K:\GitHub\adc_s5d9\EMS\synergy_cfg\ssp_cfg\driver" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\bsp" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\bsp\cmsis\Include" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\driver\api" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\driver\instances" -I"K:\GitHub\adc_s5d9\EMS\src" -I"K:\GitHub\adc_s5d9\EMS\src\synergy_gen" -I"K:\GitHub\adc_s5d9\EMS\synergy_cfg\ssp_cfg\framework" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\framework\api" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\framework\instances" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\sf_el_nx\phy" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\framework\el\nxd_application_layer" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\sf_el_nx_crypto" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\nxd_application_layer\nxd_crypto_generic" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\framework\el\nxd" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\nxd" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\nxd\nxd_src" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\nxd_application_layer\nxd_mqtt_client" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\nxd_application_layer\nxd_tls_secure" -I"K:\GitHub\adc_s5d9\EMS\synergy_cfg\ssp_cfg\framework\el" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\inc\framework\el" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\tx" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\ux" -I"K:\GitHub\adc_s5d9\EMS\synergy\ssp\src\framework\el\tx\tx_src" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" -x c "$<"
	@echo 'Finished building: $<'
	@echo ' '


